// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/jaox1/chat-server/ent/chat"
	"github.com/jaox1/chat-server/ent/message"
	"github.com/jaox1/chat-server/ent/schema"
	"github.com/jaox1/chat-server/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescDeleted is the schema descriptor for deleted field.
	chatDescDeleted := chatFields[1].Descriptor()
	// chat.DefaultDeleted holds the default value on creation for the deleted field.
	chat.DefaultDeleted = chatDescDeleted.Default.(bool)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescBody is the schema descriptor for body field.
	messageDescBody := messageFields[0].Descriptor()
	// message.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	message.BodyValidator = messageDescBody.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[1].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
